version: "3.8"

services:
    articles-bdd:
        build: ./articles-db
        image:  articles-bdd
        container_name: articles-bdd
        networks:
          - articles-network
        volumes:
          - articles-data:/var/lib/mysql
        
    articles-back:
        build: ./articles-back
        image: articles-back
        container_name: articles-back
        depends_on:
          - articles-bdd
        ports:
          - "9000:8080"
        networks:
          - articles-network
          
networks:
  articles-network:

volumes:
  articles-data:
            
 